# Generated by Django 5.0.6 on 2026-03-04 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_alter_staffprofile_department_leaveevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveevent',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaveevent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_management.staffprofile'),
        ),
    ]
