# Generated by Django 5.0.6 on 2026-03-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0004_leaveevent_status_alter_leaveevent_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='end_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
