# Generated by Django 5.0.6 on 2026-03-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0005_leaverequest_end_time_leaverequest_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
