# Generated by Django 5.0.6 on 2024-09-17 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('course', models.CharField(choices=[('Mahade Ashraf ', 'Mahade Ashraf '), ('معہد علیم', 'معہد علیم'), ('معہد ابرار', 'معہد ابرار'), ('معہد قاسم', 'معہد قاسم')], max_length=100)),
                ('branch', models.CharField(choices=[('Akber Bagh', 'Akber Bagh'), ('Khaja Bagh', 'Khaja Bagh')], max_length=100)),
                ('section', models.CharField(blank=True, choices=[('B.COM - I', 'B.COM - I'), ('B.COM - II', 'B.COM - II'), ('B.COM - III', 'B.COM - III'), ('دورۂ حدیث', 'دورۂ حدیث')], max_length=100, null=True)),
                ('monthly_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student_type', models.CharField(choices=[('Day Scholar', 'Day Scholar'), ('Boarder', 'Boarder')], default='Boarder', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_no', models.CharField(max_length=10)),
                ('receipt_no', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('receipt_type', models.CharField(choices=[('fee', 'Fee'), ('donation', 'Donation'), ('other', 'Other')], default='fee', max_length=15)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fees_collection.student')),
            ],
            options={
                'unique_together': {('book_no', 'receipt_no')},
            },
        ),
    ]
