# Generated by Django 5.0.7 on 2024-10-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_collection', '0002_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='year',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
