# Generated by Django 5.0.7 on 2024-10-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_collection', '0004_alter_payment_unique_together_alter_student_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
