# Generated by Django 5.1.1 on 2024-11-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_collection', '0008_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(),
        ),
    ]
