# Generated by Django 5.0.6 on 2025-06-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_collection', '0011_alter_student_course_alter_student_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(max_length=100),
        ),
    ]
