# Generated by Django 5.0.6 on 2026-03-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees_collection', '0013_messagelog_messagetemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetemplate',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='MessageLog',
        ),
        migrations.DeleteModel(
            name='MessageTemplate',
        ),
    ]
