# Generated by Django 5.1.4 on 2025-01-12 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('token', models.TextField()),
                ('is_master', models.BooleanField(default=False)),
                ('is_child', models.BooleanField(default=False)),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Lucky_Bulls.tradingaccount')),
            ],
        ),
    ]
