# Generated by Django 5.1.4 on 2025-02-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lucky_Bulls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='multiplier',
            field=models.FloatField(default=1.0, help_text='Trade size multiplier for child accounts'),
        ),
    ]
