# Generated by Django 5.1.4 on 2025-02-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lucky_Bulls', '0002_tradingaccount_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingaccount',
            name='multiplier',
            field=models.FloatField(blank=True, help_text='Multiplier for child accounts', null=True),
        ),
    ]
