# Generated by Django 4.2.12 on 2025-02-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lucky_Bulls', '0003_alter_tradingaccount_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='allowed_ips',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
