# Generated by Django 4.2.12 on 2025-02-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lucky_Bulls', '0004_tradingaccount_allowed_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='restrict_login',
            field=models.BooleanField(default=True, help_text='Restrict login based on IP'),
        ),
    ]
