# Generated by Django 4.2.12 on 2025-02-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lucky_Bulls', '0005_tradingaccount_restrict_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
