# Generated by Django 4.2.12 on 2025-02-12 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lucky_Bulls', '0006_processedorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_order_id', models.CharField(max_length=100)),
                ('child_order_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lucky_Bulls.tradingaccount')),
            ],
        ),
    ]
