# Generated by Django 4.2.12 on 2025-02-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lucky_Bulls', '0007_childorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('condition', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
