# Generated by Django 4.2.12 on 2025-02-15 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Lucky_Bulls', '0008_screener'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsecode', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('bsecode', models.CharField(blank=True, max_length=20, null=True)),
                ('per_chg', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('screener', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lucky_Bulls.screener')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('stocks', models.JSONField()),
                ('screener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lucky_Bulls.screener')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('timeframe', models.CharField(max_length=255)),
                ('initial_price', models.FloatField()),
                ('alert_sent', models.BooleanField(default=False)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('screener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lucky_Bulls.screener')),
            ],
        ),
    ]
