# Generated by Django 5.1.3 on 2025-02-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lucky_Bulls', '0009_stock_screenerhistory_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedorder',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='processedorder',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
