# Generated by Django 5.1.3 on 2025-02-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lucky_Bulls', '0010_processedorder_price_processedorder_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifiedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhan_client_id', models.CharField(max_length=50)),
                ('order_id', models.CharField(max_length=50)),
                ('master_order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('new_quantity', models.IntegerField()),
                ('new_price', models.FloatField(blank=True, null=True)),
                ('new_trigger_price', models.FloatField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
