# Generated by Django 5.1.3 on 2025-02-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lucky_Bulls', '0011_modifiedorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_order_id', models.CharField(max_length=100)),
                ('child_client_id', models.CharField(max_length=100)),
                ('child_order_id', models.CharField(max_length=100)),
                ('multiplier', models.FloatField()),
                ('original_quantity', models.IntegerField()),
                ('remaining_quantity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='childorder',
            name='child_account',
        ),
        migrations.DeleteModel(
            name='ProcessedOrder',
        ),
        migrations.DeleteModel(
            name='ChildOrder',
        ),
    ]
