# Generated by Django 5.1.3 on 2025-02-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lucky_Bulls', '0012_ordermapping_remove_childorder_child_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monitor Control',
                'verbose_name_plural': 'Monitor Controls',
            },
        ),
    ]
